apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: tantran0411/e-commerce-product-service
    newTag: gha-staging-39ce003

resources:
  - apps/deployment.yml
  - apps/service.yml

namespace: backend-stg
