apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: tantran0411/e-commerce-product-service
    newTag: gha-staging-0c40e7f

resources:
  - apps/deployment.yml
  - apps/service.yml

namespace: backend-stg
