apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-stg

images:
  - name: tantran0411/e-commerce-product-service
    newTag: gha-staging-8f38884

resources:
  - ../../base
