apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: backend-stg
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: 8080        # Port của Service
      targetPort: 8080  # Port của Container (Tomcat mặc định 8080)
      nodePort: 30200   # Port mở ra ngoài Node