name: Manual build ec-product-service for STG
run-name: 'Build e-commerce-product-service and push Docker image for Staging'

on:
  workflow_dispatch:

concurrency:
  group: 'manual-build-staging'
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    runs-on: stg-ci-runner-set
    environment: staging
    steps:
      - name: Discord start notification
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: 'start'
          title: '🚀 Start build e-commerce-product-service'
          message: |
            **Actor:** ${{ github.actor }}
            **Action:** Manual
            **Branch:** `${{ github.ref_name }}`

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIHUB_PAT }}
          fetch-depth: 0

      - name: Set IMAGE_TAG
        id: get-image-tag
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "image_tag=gha-staging-${{ github.ref_name }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Run Docker Build & Push
        id: docker-build-push
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/dockerhub-build-push@dev
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: "e-commerce-product-service"
          image_tag: ${{ steps.get-image-tag.outputs.image_tag }}
          dockerfile_path: "./devops/ci/docker/staging/Dockerfile"

      - name: Discord result notification
        if: always()
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: 'Build has been completed'
          message: |
            **Status:** ${{ job.status }}
            **Actor:** ${{ github.actor }}
            **Action:** Manual
            **Branch:** `${{ github.ref_name }}`
            **Image Tag:** [${{ steps.get-image-tag.outputs.image_tag || 'None' }}](${{ steps.docker-build-push.outputs.dockerhub_url }})
