name: Auto Build Back for STG
run-name: 'Build e-commerce-product-service and push image for Staging'

on:
  push:
    branches:
      - master
      - 'release/homelab/*'
    paths-ignore:
      - 'devops/**'
      - '.github/**'

concurrency:
  group: 'build-staging'
  cancel-in-progress: true

jobs:
  build-deps:
    name: e-commerce-storeback-product-service-deps
    uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/workflows/wc-reusable-build-deps.yml@dev
    permissions:
      contents: read
    secrets: inherit
    with:
      image_runtime: 'maven:3.8.4-openjdk-11-slim'
      module_path: 'common-deps-3rd'

  build-docker-image:
    needs: build-deps
    name: e-commerce-storeback-product-service
    uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/workflows/wc-reusable-auto-build-image.yml@dev
    permissions:
      contents: write
    with:
      app_name: 'e-commerce-product-service'
      gha_environment: staging
      dockerfile_path: "./devops/ci/docker/staging/Dockerfile"
      deps_cache_key: ${{ needs.build-deps.outputs.cache-key }}
    secrets: inherit
